# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grat}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sam Schenkman-Moore"]
  s.date = %q{2010-01-17}
  s.description = %q{Basic interface for making webpages with Haml and Erb. Supports nested templates.}
  s.email = %q{samsm@samsm.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "config.ru",
     "doc/created.rid",
     "doc/files/README_rdoc.html",
     "doc/fr_class_index.html",
     "doc/fr_file_index.html",
     "doc/fr_method_index.html",
     "doc/index.html",
     "doc/rdoc-style.css",
     "grat.gemspec",
     "lib/environment.rb",
     "lib/grat.rb",
     "lib/grat/content.rb",
     "lib/grat/hash_binding.rb",
     "lib/grat/system.rb",
     "public/gratfiles/application.js",
     "public/gratfiles/custom.css",
     "public/gratfiles/custom2.css",
     "public/gratfiles/einars-js-beautify/HTML-Beautify.js",
     "public/gratfiles/einars-js-beautify/beautify-cl.js",
     "public/gratfiles/einars-js-beautify/beautify-tests.js",
     "public/gratfiles/einars-js-beautify/beautify.js",
     "public/gratfiles/einars-js-beautify/bin/beautify_js",
     "public/gratfiles/einars-js-beautify/index.html",
     "public/gratfiles/einars-js-beautify/javascriptobfuscator_unpacker.js",
     "public/gratfiles/einars-js-beautify/license.txt",
     "public/gratfiles/einars-js-beautify/sanitytest.js",
     "public/gratfiles/einars-js-beautify/unmaintained/bbedit/jsBeautify_BBED.scpt",
     "public/gratfiles/einars-js-beautify/unmaintained/c-sharp/JSBeautify.cs",
     "public/gratfiles/einars-js-beautify/unmaintained/opera-userscript/make_opera_userscript.sh",
     "public/gratfiles/einars-js-beautify/unmaintained/opera-userscript/opera_userscript.js",
     "public/gratfiles/favicon.ico",
     "public/gratfiles/images/ui-bg_diagonals-thick_18_b81900_40x40.png",
     "public/gratfiles/images/ui-bg_diagonals-thick_20_666666_40x40.png",
     "public/gratfiles/images/ui-bg_flat_10_000000_40x100.png",
     "public/gratfiles/images/ui-bg_glass_100_f6f6f6_1x400.png",
     "public/gratfiles/images/ui-bg_glass_100_fdf5ce_1x400.png",
     "public/gratfiles/images/ui-bg_glass_65_ffffff_1x400.png",
     "public/gratfiles/images/ui-bg_gloss-wave_35_f6a828_500x100.png",
     "public/gratfiles/images/ui-bg_highlight-soft_100_eeeeee_1x100.png",
     "public/gratfiles/images/ui-bg_highlight-soft_75_ffe45c_1x100.png",
     "public/gratfiles/images/ui-icons_222222_256x240.png",
     "public/gratfiles/images/ui-icons_228ef1_256x240.png",
     "public/gratfiles/images/ui-icons_ef8c08_256x240.png",
     "public/gratfiles/images/ui-icons_ffd27a_256x240.png",
     "public/gratfiles/images/ui-icons_ffffff_256x240.png",
     "public/gratfiles/jquery-combined.min.js",
     "public/gratfiles/jquery-ui.css",
     "public/gratfiles/js-beautifier.min.js",
     "public/gratfiles/oocss.min.css",
     "public/gratfiles/oocss/content.css",
     "public/gratfiles/oocss/grids.css",
     "public/gratfiles/oocss/grids_debug.css",
     "public/gratfiles/oocss/libraries.css",
     "public/gratfiles/oocss/mod.css",
     "public/gratfiles/oocss/mod_debug.css",
     "public/gratfiles/oocss/mod_skins.css",
     "public/gratfiles/oocss/talk.css",
     "public/gratfiles/oocss/talk_skins.css",
     "public/gratfiles/oocss/template.css",
     "public/gratfiles/oocss/template_debug.css",
     "public/gratfiles/reset.css",
     "views/content_form.haml",
     "views/css/_content.sass",
     "views/css/_custom.sass",
     "views/css/_grids.sass",
     "views/css/_grids_debug.sass",
     "views/css/_libraries.sass",
     "views/css/_mod.sass",
     "views/css/_mod_debug.sass",
     "views/css/_mod_skins.sass",
     "views/css/_template.sass",
     "views/css/_template_debug.sass",
     "views/delete.haml",
     "views/import_form.haml",
     "views/layout.haml",
     "views/list.haml",
     "views/missing.haml",
     "views/page_list.haml"
  ]
  s.homepage = %q{http://github.com/samsm/grat}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Minimal CMS for Rack and MongoDB.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<mongo_mapper>, ["= 0.6.10"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<mongo_mapper>, ["= 0.6.10"])
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<mongo_mapper>, ["= 0.6.10"])
    s.add_dependency(%q<json>, [">= 0"])
  end
end

